# Generated by Django 5.0.6 on 2024-10-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
