# Generated by Django 5.0.6 on 2024-11-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout', '0002_alter_checkout_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='country',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='checkout',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='first_name',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='checkout',
            name='last_name',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
