# Generated by Django 5.0.6 on 2024-11-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
        ('Checkout', '0005_remove_checkout_cart_checkout_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='cart',
        ),
        migrations.AddField(
            model_name='checkout',
            name='cart',
            field=models.ManyToManyField(related_name='order', to='Cart.cart'),
        ),
    ]
