# Generated by Django 5.0.6 on 2024-11-13 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout', '0011_alter_checkout_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='cart',
        ),
    ]
